# Generated by Django 4.2.4 on 2023-08-08 22:13

from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artiste', models.CharField(max_length=200)),
                ('titre', models.CharField(max_length=200)),
                ('ipaddress', models.CharField(max_length=45)),
                ('macaddress', models.CharField(max_length=45)),
                ('unixtime', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True)),
            ],
        ),
    ]
